name: NodeCI 
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t cadastro-clientes-test .
      
      - name: Run tests with Docker
        run: docker run --rm cadastro-clientes-test npm test
      
      - name: Run application tests (integration)
        run: |
          docker-compose up -d db
          docker run --rm --network host -e NODE_ENV=test cadastro-clientes-test npm test
          docker-compose down
